# Generated by Django 3.0.8 on 2020-07-13 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Name should be 3 chars long'), django.core.validators.MaxLengthValidator(50, 'Name shoild not be longer than 50 chars')], verbose_name='Name')),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Name should be 5 chars long'), django.core.validators.MaxLengthValidator(50, 'Name shoild not be longer than 50 chars'), django.core.validators.EmailValidator('Invalid Email')], verbose_name='Email')),
            ],
        ),
    ]
